# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  eval_rest_serv
  labels:
    app:  eval_rest_serv
spec:
  selector:
    matchLabels:
      app: eval_rest_serv
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  eval_rest_serv
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  eval_rest_serv
        image:  docker.arvancloud.ir/aminmasoudii/evaluation_rest
        envFrom:
          - secretRef:
            name: eval_rest-secret
          - configMapRef:
            name: eval_rest_config
        ports:
        - containerPort:  80
          name:  eval_rest_serv
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Tehran
      restartPolicy: Always
---

